[package]
name = "ngram_models"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"           # Para muestreo de distribuciones
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"     # Para cargar africa_galore.json
