[package]
name = "tokenizers"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"                     # Para BPE
unicode-segmentation = "1.11"      # SegmentaciÃ³n de caracteres
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
